config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'scrappers#index'
  post '/scrapper', to: 'scrappers#scrapp', as: 'scrapp'
  post '/add', to: 'scrappers#create', as: 'scrapp_add'
  get '/*slug' => 'scrappers#all',
      param: :slug,
      as: 'scrapp_all',
      constraints: lambda { |req|
                     req.path.exclude? 'rails/active_storage'
                   }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scrapper.rb
class Scrapper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/ScrapingModule.rb
module ScrapingModule
  extend ActiveSupport::Concern

  def format_target_languages(target_languages)
    target_languages.join(' / ')
  end

  def check_url(url)
    return true if url.include? 'https://www.proz.com/'

    false
  end

  def scrapp_page(url)
    unparsed = HTTParty.get(url)
    doc = Nokogiri::HTML(unparsed)
    first_name = get_name(doc)[0]
    last_name = get_name(doc)[1]
    country = get_country(doc)
    native_language = get_language(doc)
    target_language = get_target_language(doc) - [native_language]
    source = url
    hash = {}
    hash['first_name'] = first_name
    hash['last_name'] = last_name
    hash['country'] = country
    hash['native_language'] = native_language
    hash['target_language'] = target_language
    hash['source'] = source
    hash
  end

  def get_name(doc)
    arr = doc.search('strong')[1].children.text.strip.split
    first_name = arr.shift
    family_name = arr.join(' ')
    [first_name, family_name]
  end

  def get_language(doc)
    lang = doc.search('.pd_bot').children.text.split[-1]
    lang[0...-1]
  end

  def get_target_language(doc)
    arr = []
    doc.search('#lang_full').children.each do |span|
      arr << span.text.split(' to ')
    end
    arr.reject(&:empty?).flatten.uniq.reject { |c| c.strip.downcase == 'less' }
  end

  def get_country(doc)
    br = doc.xpath('//span[@id="tagline"]')
    return if br.empty?

    br = br.first.next_element
    nextbr = br.next_element
    nextbr.next_element.children[0].text.split(',')[-1]
  end
end

app/controllers/concerns/Scrapping.rb
module Scrapping
  extend ActiveSupport::Concern

  def format_target_languages(target_languages)   
    target_languages.join(' / ')
  end
  
  def check_url(url)    
    if url.include? "https://www.proz.com/"
      return true
    end
    false
  end

  def scrapp_page(url)
    unparsed = HTTParty.get(url)
    doc = Nokogiri::HTML(unparsed)
    first_name = get_name(doc)[0]
    last_name = get_name(doc)[1]
    country = get_country(doc)
    native_language = get_language(doc)
    target_language = get_target_language(doc) - [native_language]
    source = url
    hash=Hash.new
    hash['first_name'] = first_name
    hash['last_name'] = last_name
    hash['country'] = country
    hash['native_language'] = native_language
    hash['target_language'] = target_language 
    hash['source'] = source
    hash
  end
 

  def get_name(doc)
    arr = doc.search('strong')[1].children.text.strip.split
    first_name = arr.shift
    family_name = arr.join(' ')
    [first_name, family_name]
  end

  def get_language(doc)
    lang = doc.search('.pd_bot').children.text.split(' ')[-1]
    lang[0...-1]
  end

  def get_target_language(doc)
    arr = []
    doc.search('#lang_full').children.each do |span|
      arr << span.text.split(' to ')
    end
    arr.reject { |c| c.empty? }.flatten.uniq.reject { |c| c.strip.downcase == 'less' }
  end

  def get_country(doc)
     br = doc.xpath('//span[@id="tagline"]')
     return if br.empty?
    br =  br.first.next_element
    nextbr =br.next_element
    location = nextbr.next_element.children[0].text.split(',')[-1]
  end
  
end

app/controllers/concerns/scraping_module.rb
module ScrapingModule
  extend ActiveSupport::Concern

  def format_target_languages(target_languages)
    target_languages.join(' / ')
  end

  def check_url(url)
    return true if url.include? 'https://www.proz.com/'

    false
  end

  def scrapp_page(url)
    unparsed = HTTParty.get(url)
    doc = Nokogiri::HTML(unparsed)
    first_name = name(doc)[0]
    last_name = name(doc)[1]
    country = country(doc)
    native_language = language(doc)
    target_language = target_language(doc) - [native_language]
    source = url
    hash = {}
    hash['first_name'] = first_name
    hash['last_name'] = last_name
    hash['country'] = country
    hash['native_language'] = native_language
    hash['target_language'] = target_language
    hash['source'] = source
    hash
  end

  def name(doc)
    arr = doc.search('strong')[1]
    return if arr.nil?

    text = arr.children.text.strip.split
    first_name = text.shift
    family_name = text.join(' ')
    [first_name, family_name]
  end

  def language(doc)
    lang = doc.search('.pd_bot').children.text.split[-1]

    return 'No language defined' if lang[0...-1] == 'languages'

    lang[0...-1]
  end

  def target_language(doc)
    arr = []
    doc.search('#lang_full').children.each do |span|
      arr << span.text.split(' to ')
    end
    arr.reject(&:empty?).flatten.uniq.reject { |c| c.strip.downcase == 'less' }
  end

  def country(doc)
    br = doc.xpath('//span[@id="tagline"]')
    return if br.empty?

    br = br.first.next_element
    nextbr = br.next_element
    nextbr.next_element.children[0].text.split(',')[-1]
  end
end

app/controllers/scrappers_controller.rb
class ScrappersController < ApplicationController
  include ScrapingModule
  def index; end

  def scrapp
    profile_url = params[:proz_profile_url]
    return redirect_to root_path unless check_url(profile_url)

    @scraped_values = scrapp_page(profile_url)
  end

  def create
    target_languages = format_target_languages(params[:languages])
    @scrapp = Scrapper.new(
      first_name: params['first_name'],
      last_name: params['last_name'],
      country: params['country'],
      native_language: params['native_language'],
      target_language: target_languages, source:  params['source']
    )
    redirect_to '/all-scrped-data' if @scrapp.save
  end

  def all
    @scrapped = Scrapper.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrappers_helper.rb
module ScrappersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travod</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Warning !! ensure that "stylesheet_pack_tag" is used, line below -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/scrapper/index.html.erb
  
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1">Scrapper</h1>
          <p class="h6 font-weight-bold">Paste the url of the person on www.proz.com</p>
          <div class="d-flex ">
            <%= form_with url: scrapp_path, method: :post,class: "d-flex w-100" do |form| %>
            <%= form.text_field :proz_profile_url,class: "form-control form-control-lg rounded-0" %>
            <%= form.submit "Extract",class: "btn btn-primary  rounded-0" %>
          <% end %>
      </div>
    </div>
  </section>
</main> 

app/views/scrappers/all.html.erb
<h2 class="text-center text-uppercase">All scraped data</h2>
<div class="row d-flex justify-content-center">
 <div class="col-10">
<% @scrapped.each do |t|%>
   <div  class="list-group-item list-group-item-action py-3 lh-tight">
     <div class="d-flex w-100 align-items-center justify-content-between">
        <div class="col-sm d-flex flex-column"> 
          <h5 class="mb-1">Full Name</h5>
          <strong class="mb-1"><%= t.first_name%> <%= t.last_name%></strong>
        </div>

        <div class="col-sm align-items-center text-center"> 
          <strong class="mr-4">Native language:</strong>
          <span class="mb-1"><%= t.native_language%></span>
        </div>


        <div class="col-sm d-flex flex-column align-items-end">
          <strong class="mr-4">Country</strong>
          <span class="mb-1"><%= t.country%></span>
        </div>  

      </div> 

        <div class="py-2"> 
          <strong class="mr-4 pl-2">Target Languages: </strong>
          <span class="mb-1"><%= t.target_language%></span>
        </div> 

          <div class="bg-light d-flex justify-content-between py-3"> 
          <strong class="mr-4 px-2">Source: </strong>
          <span class="text-center"><%= t.source%></span>
        </div> 
    </div>

<%end%>
<%= link_to  "return to main page" , root_path,class: 'btn btn-primary rounded-0 text-uppercase w-100 mb-5' %>
 </div>
</div>

 

app/views/scrappers/index.html.erb
 
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1">Scrapper</h1>
          <p class="h6 font-weight-bold">Paste the url of the person on www.proz.com</p>
          <div class="d-flex ">
            <%= form_with url: scrapp_path, method: :post,class: "d-flex w-100" do |form| %>
            <%= form.text_field :proz_profile_url,class: "form-control form-control-lg rounded-0" %>
            <%= form.submit "Extract",class: "btn btn-primary  rounded-0" %>
          <% end %>
      </div>
    </div>
  </section>
 

app/views/scrappers/scrapp.html.erb
<h2 class="text-decoration-none text-center">Scrapped data for <%= @scraped_values["first_name"]%> 
  <%= @scraped_values["last_name"]%> 
</h2>
<div class="row g-5 d-flex justify-content-center">
 <div class="col-md-7 col-lg-8">
  
   <%= form_with url: scrapp_add_path, method: :post do |f| %>

  <div class="row g-3">

    <div class="col-sm-6">
     <%= f.label "First name",class: 'form-label' %>
     <%= f.text_field :first_name,class: 'form-control',value:   @scraped_values["first_name"] %>
    </div>
    
    <div class="col-sm-6">
      <%= f.label "Last name",class: 'form-label' %>
      <%= f.text_field :last_name,class: 'form-control',value: @scraped_values["last_name"] %>
    </div>

     <div class="col-sm-6">
      <%= f.label "Country",class: 'form-label'  %>
      <%= f.text_field :country,class: 'form-control',value: @scraped_values["country"] %>
    </div>

    <div class="col-sm-6">
      <%= f.label "Native language",class: 'form-label' %>
      <%= f.text_field :native_language,class: 'form-control',value: @scraped_values["native_language"] %>
    </div>

  </div>
  
    <div class="col-sm-12">

      <%= f.label "Target languages",class: 'form-label pt-4 ' %> 
        <%@scraped_values["target_language"].each do |lang,indx|%>
        <div class="col-sm-12 my-2">
          <%= f.text_field :languages,class: 'form-control',value: lang, multiple: true %> 
        </div>
        <%end%> 


        <%= f.label "Source",class: 'form-label' %>
      <%= f.text_field :source,class: 'form-control my-2',value: @scraped_values["source"] %>
    </div>
    <div class="row">  
      <div class="col-6">
    <%= f.submit "Save", class: "btn btn-success text-uppercase rounded-0 w-100" %>
      </div>
       <div class="col-6">   <%= link_to  "back to main page", root_path,class: 'btn btn-dark text-uppercase rounded-0 w-100' %>
    </div>
    </div>
    
  <% end %>
 </div>
 
</div>



   
 
 
 